//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vohmencev_ComputerSoft.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public int OrderInfo { get; set; }
        public string Equipment { get; set; }
        public string Repair { get; set; }
    
        public virtual ComputerEquipment ComputerEquipment { get; set; }
        public virtual OrderInfo OrderInfo1 { get; set; }
        public virtual RepairType RepairType { get; set; }
    }
}
